FROM public.ecr.aws/docker/library/alpine:3.22.0

WORKDIR /opt/az-agent

COPY scripts/install-tools.sh /temp/install-tools.sh
COPY scripts/start.sh /start.sh

RUN addgroup -S azp && adduser -S azp -G azp

RUN chmod +x /temp/install-tools.sh /start.sh \
    && sh /temp/install-tools.sh && rm -rf /temp/install-tools.sh\
    && chown -R azp:azp /opt/az-agent 

USER azp

ENTRYPOINT [ "/start.sh" ]